load("@io_bazel_rules_d//d:d.bzl", "d_test", "ldc2_test")

d_test(
    name = "fiber_thread_usage",
    srcs = ["fiber_thread_usage.d"],
)

ldc2_test(
    name = "fiber_thread_usage_ldc2",
    srcs = ["fiber_thread_usage.d"],
)
