package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_d//d:d.bzl", "d_library", "ldc2_library")

d_library(
    name = "simple_d_library",
    srcs = ["simple_library.d"],
)

ldc2_library(
    name = "simple_d_library_ldc2",
    srcs = ["simple_library.d"],
)
